-- 1. Create canonical ingredient table
CREATE TABLE public.ingredient (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  category varchar
);

-- Case-insensitive unique constraint on ingredient name
CREATE UNIQUE INDEX ingredient_name_unique ON public.ingredient (LOWER(name));

-- 2. Enable RLS on ingredient table
ALTER TABLE public.ingredient ENABLE ROW LEVEL SECURITY;

-- Anyone can view ingredients
CREATE POLICY "Anyone can view ingredients"
ON public.ingredient
FOR SELECT
USING (true);

-- Authenticated users can insert ingredients
CREATE POLICY "Authenticated users can insert ingredients"
ON public.ingredient
FOR INSERT
WITH CHECK (auth.uid() IS NOT NULL);

-- Only admins can update ingredients
CREATE POLICY "Admins can update ingredients"
ON public.ingredient
FOR UPDATE
USING ((SELECT public.is_admin()));

-- Only admins can delete ingredients
CREATE POLICY "Admins can delete ingredients"
ON public.ingredient
FOR DELETE
USING ((SELECT public.is_admin()));

-- 3. Add nullable ingredient_id FK to recipe_ingredient
ALTER TABLE public.recipe_ingredient
  ADD COLUMN ingredient_id bigint REFERENCES public.ingredient(id);
